version: '3.3'
services:
  db-develop:
    image: $DB_IMAGE:$DB_VERSION
    container_name: db-develop
    restart: always
    ports:
      - $DB_PORT:5432
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=postgres
    volumes:
      - database:$DB_CONTAINER_PATH
    networks:
      - develop-network
  odoo-develop:
    image: $ODOO_IMAGE:$ODOO_VERSION
    container_name: odoo-develop
    restart: always
    depends_on:
      - db-develop
    links:
      - db-develop
      - wdb
    ports:
      - $ODOO_PORT:8069
      - 3000:3000
    volumes:
     # - $ODOO_PATH/$ODOO_VERSION/$CONF_LOCAL_PATH:$CONF_CONTAINER_PATH
      - /home/sandro/programacion/odoo-docker-build/odoo-develop/13.0/conf:$CONF_CONTAINER_PATH
      - /home/sandro/programacion/odoo-docker-build/odoo-develop/13.0/extra-addons:$EXTRA_ADDONS_CONTAINER_PATH
      - filestore:$ODOO_FILESTORE_CONTAINER_PATH
      - /home/sandro/programacion/odoo-docker-build/odoo-develop/13.0/src:$ODOO_CONTAINER_SRC
      - odoo_datos:/opt/odoo/data
    command: odoo --dev=reload,qweb,werkzeug,xml
    networks:
      - develop-network
    environment:
      - DB_PORT_5432_TCP_ADDR=db-develop
      - DB_PORT_5432_TCP_PORT=5432
      - DB_ENV_POSTGRES_USER=$DB_USER
      - DB_ENV_POSTGRES_PASSWORD=$DB_PASSWORD
      - DB_ENV_POSTGRES_DB=postgres
      - ADMIN_PASS=$ODOO_ADMIN_PASS
      - WDB_NO_BROWSER_AUTO_OPEN:True
      - WDB_SOCKET_SERVER:wdb
      - WDB_WEB_PORT:1984
      - WDB_WEB_SERVER:localhost
  pgadmin4-develop:
    image: $PGADMIN_IMAGE:$PGADMIN_VERSION
    container_name: pgadmin4-develop
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_MAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD
    ports:
      - $PGADMIN_PORT:80
    volumes:
      - pgadmin4:$PGADMIN_CONTAINER_PATH
      - pgadmin4_data:$PGADMIN_DATA_PATH
    depends_on:
      - db-develop
    links:
      - db-develop
    networks:
      - develop-network
    restart: always
  wdb:
    image: kozea/wdb
    container_name: wdb
    ports:
      - "1984:1984"
    networks:
      - develop-network
    restart: always
networks:
  develop-network:
    driver: bridge
volumes:
  database:
  filestore:
  pgadmin4:
  pgadmin4_data:
  odoo_datos:
